version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: Scripts/ecrLogin
  AfterInstall:
    - location: Scripts/runDockerContainer
  ApplicationStop:
    - location: Scripts/stopServer


# wget https://aws-codedeploy-us-west-1.s3.us-west-1.amazonaws.com/latest/install